spring:
  application:
    name: spring-boot-essetials-security
  datasource:
    url: jdbc:mysql://localhost:3306/spring-essetials?createDatabaseIfNotExist=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASS}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect

